import type {
  Profile,
  TargetType,
  TargetProfile,
  DryRunResult,
  DryRunChange,
  BackupRecord,
  HealthStatus,
} from '@/types';
import { RESTORE_SUPPORTED_TARGETS, TARGET_CONFIG_PATHS } from '@/types';
import { knownTargets } from '@/data/mock';
import { exists, mkdir, readTextFile, writeTextFile } from '@tauri-apps/plugin-fs';
import { appConfigDir, homeDir } from '@tauri-apps/api/path';

export interface TargetAdapter {
  read(targetType: TargetType): Promise<string>;
  write(targetType: TargetType, profile: Profile | TargetProfile): Promise<void>;
  backup(
    targetType: TargetType,
    profileId: string,
    profileName: string
  ): Promise<BackupRecord | null>;
  diff(
    targetType: TargetType,
    profile: Profile | TargetProfile,
    currentContent: string
  ): DryRunChange | null;
}

async function resolveHomePath(relativePath: string): Promise<string> {
  const home = await homeDir();
  const cleanPath = relativePath.replace(/^~/, '');
  return `${home}${cleanPath}`;
}

async function readRawConfig(targetType: TargetType): Promise<string | null> {
  const path = TARGET_CONFIG_PATHS[targetType];
  if (path === 'Environment variables') {
    return JSON.stringify({});
  }
  const fullPath = await resolveHomePath(path);
  try {
    return await readTextFile(fullPath);
  } catch {
    return null;
  }
}

async function writeRawConfig(targetType: TargetType, content: string): Promise<void> {
  const path = TARGET_CONFIG_PATHS[targetType];
  if (path === 'Environment variables') {
    throw new Error('Writing environment variables is not supported directly');
  }
  const fullPath = await resolveHomePath(path);
  const dirPath = fullPath.split('/').slice(0, -1).join('/');
  const dirExists = await exists(dirPath);
  if (!dirExists) {
    await mkdir(dirPath, { recursive: true });
  }
  await writeTextFile(fullPath, content);
}

async function computeChecksum(content: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(content);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

async function createBackupRecord(
  targetType: TargetType,
  originalContent: string,
  profileId: string,
  profileName: string
): Promise<BackupRecord> {
  const appConfig = await appConfigDir();
  const backupDir = `${appConfig}agent-env-switcher/backups`;
  const dirExists = await exists(backupDir);
  if (!dirExists) {
    await mkdir(backupDir, { recursive: true });
  }
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupFileName = `${targetType}-${timestamp}.bak`;
  const backupPath = `${backupDir}/${backupFileName}`;
  await writeTextFile(backupPath, originalContent);

  const checksum = await computeChecksum(originalContent);
  const target = knownTargets.find((t) => t.type === targetType);

  return {
    id: `backup-${targetType}-${Date.now()}`,
    targetType,
    targetName: target?.name || targetType,
    profileId,
    profileName,
    createdAt: new Date().toISOString(),
    originalConfigPath: TARGET_CONFIG_PATHS[targetType] || 'Unknown',
    backupFilePath: backupPath,
    backupFileSize: new Blob([originalContent]).size,
    restoreSupported: (RESTORE_SUPPORTED_TARGETS as readonly string[]).includes(targetType),
    checksum,
  };
}

function formatHermesYaml(profile: Profile | TargetProfile): string {
  const provider = profile.providerType;
  const baseUrl = profile.baseUrl;
  const defaultModel = profile.defaultModel;
  const fastModel = profile.fastModel;
  const reasoningModel = profile.reasoningModel;
  const apiKey = profile.apiKey;

  return `# Generated by Agent Env Switcher
# DO NOT edit manually while using profile management

model:
  provider: ${provider}
  default: ${defaultModel}
  base_url: ${baseUrl}

providers:
  ${provider}:
    base_url: ${baseUrl}
    api_key: ${apiKey}

model_aliases:
  fast: ${fastModel}
  reasoning: ${reasoningModel}
`;
}

function parseHermesYaml(content: string): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  const lines = content.split('\n');
  let currentSection = '';
  let currentSubSection = '';

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const sectionMatch = trimmed.match(/^(\w+):\s*$/);
    if (sectionMatch) {
      currentSection = sectionMatch[1];
      currentSubSection = '';
      if (!result[currentSection]) result[currentSection] = {};
      continue;
    }

    const kvMatch = trimmed.match(/^(\w+):\s+(.+)$/);
    if (kvMatch) {
      const key = kvMatch[1];
      let value: string | number = kvMatch[2];
      if (!isNaN(Number(value)) && value !== '') value = Number(value);

      if (currentSection && currentSubSection) {
        const section = result[currentSection] as Record<string, unknown>;
        const sub = (section[currentSubSection] as Record<string, unknown>) || {};
        sub[key] = value;
        section[currentSubSection] = sub;
      } else if (currentSection) {
        const section = result[currentSection] as Record<string, unknown>;
        if (typeof value === 'string' && !isNaN(Number(value)) && value !== '') {
          section[key] = Number(value);
        } else {
          section[key] = value;
        }
      } else {
        result[key] = value;
      }
      continue;
    }

    const subSectionMatch = trimmed.match(/^  (\w+):\s*$/);
    if (subSectionMatch && currentSection) {
      currentSubSection = subSectionMatch[1];
      const section = result[currentSection] as Record<string, unknown>;
      if (!section[currentSubSection]) section[currentSubSection] = {};
    }
  }

  return result;
}

function mergeHermesYaml(
  existing: Record<string, unknown>,
  profile: Profile | TargetProfile
): string {
  const model = (existing.model as Record<string, unknown>) || {};
  model.provider = profile.providerType;
  model.default = profile.defaultModel;
  model.base_url = profile.baseUrl;
  existing.model = model;

  const providers = (existing.providers as Record<string, unknown>) || {};
  const providerConfig = (providers[profile.providerType] as Record<string, unknown>) || {};
  providerConfig.base_url = profile.baseUrl;
  providerConfig.api_key = profile.apiKey;
  providers[profile.providerType] = providerConfig;
  existing.providers = providers;

  const aliases = (existing.model_aliases as Record<string, unknown>) || {};
  aliases.fast = profile.fastModel;
  aliases.reasoning = profile.reasoningModel;
  existing.model_aliases = aliases;

  let output = '# Generated by Agent Env Switcher\n\n';

  if (existing.model) {
    output += 'model:\n';
    const m = existing.model as Record<string, unknown>;
    for (const [k, v] of Object.entries(m)) {
      output += `  ${k}: ${v}\n`;
    }
    output += '\n';
  }

  if (existing.providers) {
    output += 'providers:\n';
    const p = existing.providers as Record<string, unknown>;
    for (const [provName, provConfig] of Object.entries(p)) {
      output += `  ${provName}:\n`;
      const pc = provConfig as Record<string, unknown>;
      for (const [k, v] of Object.entries(pc)) {
        output += `    ${k}: ${v}\n`;
      }
    }
    output += '\n';
  }

  if (existing.model_aliases) {
    output += 'model_aliases:\n';
    const a = existing.model_aliases as Record<string, unknown>;
    for (const [k, v] of Object.entries(a)) {
      output += `  ${k}: ${v}\n`;
    }
  }

  return output;
}

/**
 * Extract the current model value from real Codex config.toml.
 * The real format has `model = "gpt-5.5"` as a top-level key.
 */
function parseCodexConfigModel(content: string): string | null {
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    const match = trimmed.match(/^model\s*=\s*"(.+?)"\s*$/);
    if (match) return match[1];
  }
  return null;
}

/**
 * Update only the `model = "..."` line in real Codex config.toml.
 * Preserves all other lines exactly (comments, sections, formatting).
 */
function updateCodexConfigModel(content: string, newModel: string): string {
  const lines = content.split('\n');
  let found = false;
  const result = lines.map((line) => {
    const trimmed = line.trim();
    if (!found && trimmed.match(/^model\s*=\s*".*"\s*$/)) {
      found = true;
      return line.replace(/model\s*=\s*".*"/, `model = "${newModel}"`);
    }
    return line;
  });
  if (!found) {
    // No existing model line; add at top
    result.unshift(`model = "${newModel}"`);
  }
  return result.join('\n');
}

/**
 * Generate a minimal Codex config.toml with just the model line.
 * Used when no config exists yet.
 */
function generateCodexConfig(model: string): string {
  return `model = "${model}"\n`;
}

interface CodexAuthData {
  auth_mode: string;
  OPENAI_API_KEY: string | null;
  OPENAI_BASE_URL?: string;
  tokens?: Record<string, string>;
  last_refresh?: string;
  [key: string]: unknown;
}

/**
 * Read and parse ~/.codex/auth.json
 */
async function readCodexAuth(): Promise<CodexAuthData | null> {
  const home = await homeDir();
  const authPath = `${home}.codex/auth.json`;
  try {
    const content = await readTextFile(authPath);
    return JSON.parse(content) as CodexAuthData;
  } catch {
    return null;
  }
}

/**
 * Update API key in ~/.codex/auth.json.
 * Sets auth_mode to "api-key" and OPENAI_API_KEY to the given key.
 * Preserves all other fields (tokens, etc.) so user can switch back.
 */
async function writeCodexAuth(apiKey: string, baseUrl?: string): Promise<void> {
  const home = await homeDir();
  const authPath = `${home}.codex/auth.json`;
  let existing: CodexAuthData = { auth_mode: 'api-key', OPENAI_API_KEY: apiKey };

  try {
    const content = await readTextFile(authPath);
    existing = JSON.parse(content) as CodexAuthData;
  } catch {
    // No existing auth.json; create fresh
  }

  existing.auth_mode = 'api-key';
  existing.OPENAI_API_KEY = apiKey;
  if (baseUrl) {
    existing.OPENAI_BASE_URL = baseUrl;
  }

  const dirPath = `${home}.codex`;
  const dirExists = await exists(dirPath);
  if (!dirExists) {
    await mkdir(dirPath, { recursive: true });
  }
  await writeTextFile(authPath, JSON.stringify(existing, null, 2));
}

function formatClaudeCodeConfig(profile: Profile | TargetProfile): string {
  const config: Record<string, unknown> = {
    provider: profile.providerType,
    baseUrl: profile.baseUrl,
    apiKey: profile.apiKey,
    models: {
      default: profile.defaultModel,
      fast: profile.fastModel,
      reasoning: profile.reasoningModel,
    },
  };
  return JSON.stringify(config, null, 2);
}

function generateClaudeCodeEnvExport(profile: Profile | TargetProfile): string {
  return `# Claude Code Environment Variables
# Generated by Agent Env Switcher
# Source this file: source ~/.claude/.env

export ANTHROPIC_BASE_URL="${profile.baseUrl}"
export ANTHROPIC_AUTH_TOKEN="${profile.apiKey}"
export ANTHROPIC_MODEL="${profile.defaultModel}"
`;
}

function formatOpenClawConfig(profile: Profile | TargetProfile): string {
  const config: Record<string, unknown> = {
    provider: profile.providerType,
    baseUrl: profile.baseUrl,
    apiKey: profile.apiKey,
    model: profile.defaultModel,
    fastModel: profile.fastModel,
    reasoningModel: profile.reasoningModel,
  };
  return JSON.stringify(config, null, 2);
}

function formatConfigForDiff(
  targetType: TargetType,
  profile: Profile | TargetProfile,
): string {
  switch (targetType) {
    case 'claude-code':
      return formatClaudeCodeConfig(profile);
    case 'hermes':
      return formatHermesYaml(profile);
    case 'codex':
      return `model = "${profile.defaultModel}"`;
    case 'openclaw':
      return formatOpenClawConfig(profile);
    case 'openai-compatible-api':
      return JSON.stringify(
        {
          OPENAI_API_KEY: profile.apiKey,
          OPENAI_BASE_URL: profile.baseUrl,
          OPENAI_MODEL: profile.defaultModel,
        },
        null,
        2
      );
    default:
      return '';
  }
}

function createDiff(
  targetType: TargetType,
  beforeContent: string,
  afterContent: string
): DryRunChange | null {
  if (beforeContent.trim() === afterContent.trim()) return null;
  return {
    file: TARGET_CONFIG_PATHS[targetType] || 'Unknown',
    action: beforeContent.trim() ? 'modify' : 'create',
    before: beforeContent,
    after: afterContent,
  };
}

export const targetAdapter: TargetAdapter = {
  async read(targetType: TargetType): Promise<string> {
    const raw = await readRawConfig(targetType);
    return raw || '';
  },

  async write(targetType: TargetType, profile: Profile | TargetProfile): Promise<void> {
    if (targetType === 'openai-compatible-api') {
      throw new Error('OpenAI-compatible API config is env-var based; generate export instead');
    }

    const currentContent = await this.read(targetType);
    let content: string;

    switch (targetType) {
      case 'hermes': {
        let existing: Record<string, unknown> = {};
        if (currentContent.trim()) {
          existing = parseHermesYaml(currentContent);
        }
        content = mergeHermesYaml(existing, profile);
        break;
      }
      case 'codex': {
        if (currentContent.trim()) {
          content = updateCodexConfigModel(currentContent, profile.defaultModel);
        } else {
          content = generateCodexConfig(profile.defaultModel);
        }
        break;
      }
      case 'claude-code': {
        let existing: Record<string, unknown> = {};
        if (currentContent.trim()) {
          try {
            existing = JSON.parse(currentContent);
          } catch {
            throw new Error(
              'Claude Code existing config is invalid JSON; cannot safely merge'
            );
          }
        }
        const merged = {
          ...existing,
          provider: profile.providerType,
          baseUrl: profile.baseUrl,
          apiKey: profile.apiKey,
          models: {
            ...(typeof existing.models === 'object' && existing.models !== null
              ? (existing.models as Record<string, unknown>)
              : {}),
            default: profile.defaultModel,
            fast: profile.fastModel,
            reasoning: profile.reasoningModel,
          },
        };
        content = JSON.stringify(merged, null, 2);
        break;
      }
      case 'openclaw': {
        let existing: Record<string, unknown> = {};
        if (currentContent.trim()) {
          try {
            existing = JSON.parse(currentContent);
          } catch {
            throw new Error(
              'OpenClaw existing config is invalid JSON; cannot safely merge'
            );
          }
        }
        const merged = {
          ...existing,
          provider: profile.providerType,
          baseUrl: profile.baseUrl,
          apiKey: profile.apiKey,
          model: profile.defaultModel,
          fastModel: profile.fastModel,
          reasoningModel: profile.reasoningModel,
        };
        content = JSON.stringify(merged, null, 2);
        break;
      }
      default:
        throw new Error(`Unsupported target type: ${targetType}`);
    }

    await writeRawConfig(targetType, content);

    if (targetType === 'claude-code') {
      const envContent = generateClaudeCodeEnvExport(profile);
      const home = await homeDir();
      const envPath = `${home}.claude/.env`;
      const dirPath = envPath.split('/').slice(0, -1).join('/');
      const dirExists = await exists(dirPath);
      if (!dirExists) {
        await mkdir(dirPath, { recursive: true });
      }
      await writeTextFile(envPath, envContent);
    }

    if (targetType === 'codex' && profile.apiKey) {
      await writeCodexAuth(profile.apiKey, profile.baseUrl);
    }
  },

  async backup(
    targetType: TargetType,
    profileId: string,
    profileName: string
  ): Promise<BackupRecord | null> {
    const raw = await readRawConfig(targetType);
    if (!raw) return null;

    // For codex, also include auth.json in the backup
    if (targetType === 'codex') {
      const auth = await readCodexAuth();
      const combined = JSON.stringify({ config: raw, auth }, null, 2);
      return await createBackupRecord(targetType, combined, profileId, profileName);
    }

    return await createBackupRecord(targetType, raw, profileId, profileName);
  },

  diff(
    targetType: TargetType,
    profile: Profile | TargetProfile,
    currentContent: string
  ): DryRunChange | null {
    const after = formatConfigForDiff(targetType, profile);
    return createDiff(targetType, currentContent, after);
  },
};

export function generateClaudeCodeEnvExportContent(profile: Profile | TargetProfile): string {
  return generateClaudeCodeEnvExport(profile);
}

export async function generateDryRun(profile: Profile): Promise<DryRunResult[]> {
  const results: DryRunResult[] = [];
  for (const targetType of profile.enabledTargets) {
    const target = knownTargets.find((t) => t.type === targetType);
    let status: DryRunResult['status'] = 'pending';
    let changes: DryRunChange[] = [];

    try {
      const currentContent = await targetAdapter.read(targetType);
      const change = targetAdapter.diff(targetType, profile, currentContent);
      if (change) {
        changes = [change];
        status = 'ready';
      }
    } catch (err) {
      status = 'failed';
      changes = [
        {
          file: TARGET_CONFIG_PATHS[targetType] || 'Unknown',
          action: 'modify',
          before: '',
          after: `Error: ${err instanceof Error ? err.message : String(err)}`,
        },
      ];
    }

    results.push({
      id: `dryrun-${profile.id}-${targetType}-${Date.now()}`,
      profileId: profile.id,
      profileName: profile.name,
      targetType,
      targetName: target?.name || targetType,
      timestamp: new Date().toISOString(),
      changes,
      status,
    });
  }
  return results;
}

export async function generateTargetProfileDryRun(
  profile: TargetProfile
): Promise<DryRunResult> {
  const target = knownTargets.find((t) => t.type === profile.targetType);
  let status: DryRunResult['status'] = 'pending';
  let changes: DryRunChange[] = [];

  try {
    const currentContent = await targetAdapter.read(profile.targetType);
    const change = targetAdapter.diff(profile.targetType, profile, currentContent);
    if (change) {
      changes = [change];
      status = 'ready';
    }
  } catch (err) {
    status = 'failed';
    changes = [
      {
        file: TARGET_CONFIG_PATHS[profile.targetType] || 'Unknown',
        action: 'modify',
        before: '',
        after: `Error: ${err instanceof Error ? err.message : String(err)}`,
      },
    ];
  }

  return {
    id: `dryrun-${profile.id}-${profile.targetType}-${Date.now()}`,
    profileId: profile.id,
    profileName: profile.name,
    targetType: profile.targetType,
    targetName: target?.name || profile.targetType,
    timestamp: new Date().toISOString(),
    changes,
    status,
  };
}

export async function applyProfile(profile: Profile): Promise<{
  success: boolean;
  errors: string[];
  warnings: string[];
  backupRecords: BackupRecord[];
  appliedTargets: TargetType[];
}> {
  const errors: string[] = [];
  const warnings: string[] = [];
  const backupRecords: BackupRecord[] = [];
  const appliedTargets: TargetType[] = [];
  for (const targetType of profile.enabledTargets) {
    if (targetType === 'openai-compatible-api') {
      warnings.push(
        'OpenAI-compatible API config changes skipped (environment variable modification not supported)'
      );
      continue;
    }
    try {
      const backup = await targetAdapter.backup(targetType, profile.id, profile.name);
      if (backup) backupRecords.push(backup);
      await targetAdapter.write(targetType, profile);
      appliedTargets.push(targetType);
    } catch (err) {
      errors.push(`${targetType}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return {
    success: errors.length === 0 && appliedTargets.length > 0,
    errors,
    warnings,
    backupRecords,
    appliedTargets,
  };
}

export async function applyTargetProfile(profile: TargetProfile): Promise<{
  success: boolean;
  error?: string;
  backupRecord?: BackupRecord;
}> {
  try {
    const backup = await targetAdapter.backup(
      profile.targetType,
      profile.id,
      profile.name
    );
    await targetAdapter.write(profile.targetType, profile);
    return { success: true, backupRecord: backup || undefined };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export async function restoreBackup(backupRecord: BackupRecord): Promise<{
  success: boolean;
  error?: string;
  preRestoreBackup?: BackupRecord;
}> {
  if (!backupRecord.restoreSupported) {
    return {
      success: false,
      error: `Restore not supported for target: ${backupRecord.targetType}`,
    };
  }

  const backupExists = await exists(backupRecord.backupFilePath);
  if (!backupExists) {
    return { success: false, error: `Backup file not found: ${backupRecord.backupFilePath}` };
  }

  let backupContent: string;
  try {
    backupContent = await readTextFile(backupRecord.backupFilePath);
  } catch {
    return { success: false, error: `Failed to read backup file: ${backupRecord.backupFilePath}` };
  }

  if (
    backupRecord.targetType === 'claude-code' ||
    backupRecord.targetType === 'openclaw'
  ) {
    try {
      JSON.parse(backupContent);
    } catch {
      return { success: false, error: 'Backup content is invalid JSON; cannot safely restore' };
    }
  }

  let preRestoreBackup: BackupRecord | undefined;
  const currentContent = await readRawConfig(backupRecord.targetType);
  if (currentContent) {
    try {
      preRestoreBackup = await createBackupRecord(
        backupRecord.targetType,
        currentContent,
        backupRecord.profileId,
        backupRecord.profileName
      );
    } catch {
      return { success: false, error: 'Failed to create pre-restore backup; aborting restore' };
    }
  }

  try {
    // Codex backups contain combined JSON with { config, auth }
    if (backupRecord.targetType === 'codex') {
      try {
        const combined = JSON.parse(backupContent) as { config?: string; auth?: CodexAuthData };
        if (combined.config) {
          await writeRawConfig(backupRecord.targetType, combined.config);
        }
        if (combined.auth?.OPENAI_API_KEY) {
          await writeCodexAuth(combined.auth.OPENAI_API_KEY, combined.auth.OPENAI_BASE_URL);
        }
      } catch {
        // Fallback: treat as raw config.toml content
        await writeRawConfig(backupRecord.targetType, backupContent);
      }
    } else {
      await writeRawConfig(backupRecord.targetType, backupContent);
    }
  } catch (err) {
    return {
      success: false,
      error: `Failed to write restored config: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  return { success: true, preRestoreBackup };
}

export async function previewRestore(backupRecord: BackupRecord): Promise<{
  canRestore: boolean;
  error?: string;
  diff: DryRunChange | null;
}> {
  if (!backupRecord.restoreSupported) {
    return {
      canRestore: false,
      error: `Restore not supported for target: ${backupRecord.targetType}`,
      diff: null,
    };
  }

  const backupExists = await exists(backupRecord.backupFilePath);
  if (!backupExists) {
    return {
      canRestore: false,
      error: `Backup file not found: ${backupRecord.backupFilePath}`,
      diff: null,
    };
  }

  let backupContent: string;
  try {
    backupContent = await readTextFile(backupRecord.backupFilePath);
  } catch {
    return { canRestore: false, error: 'Failed to read backup file', diff: null };
  }

  if (
    backupRecord.targetType === 'claude-code' ||
    backupRecord.targetType === 'openclaw'
  ) {
    try {
      JSON.parse(backupContent);
    } catch {
      return {
        canRestore: false,
        error: 'Backup content is invalid JSON; cannot safely restore',
        diff: null,
      };
    }
  }

  // For codex, extract config from combined backup
  let displayContent = backupContent;
  if (backupRecord.targetType === 'codex') {
    try {
      const combined = JSON.parse(backupContent) as { config?: string };
      if (combined.config) displayContent = combined.config;
    } catch {
      // Not combined format; use as-is
    }
  }

  const currentContent = await readRawConfig(backupRecord.targetType);
  const diff = createDiff(backupRecord.targetType, currentContent || '', displayContent);

  return { canRestore: true, diff };
}

export async function checkTargetHealth(targetType: TargetType): Promise<HealthStatus> {
  if (targetType === 'openai-compatible-api') {
    return 'unknown';
  }

  const path = TARGET_CONFIG_PATHS[targetType];
  const fullPath = await resolveHomePath(path);
  const fileExists = await exists(fullPath);
  if (!fileExists) return 'unknown';

  try {
    const content = await readTextFile(fullPath);

    if (targetType === 'hermes') {
      if (content.includes('provider:') && content.includes('model:')) return 'healthy';
      return 'warning';
    }

    if (targetType === 'codex') {
      // Real format: top-level `model = "..."` key
      if (/^model\s*=\s*".+"/m.test(content)) return 'healthy';
      return 'warning';
    }

    const parsed = JSON.parse(content);
    if (typeof parsed !== 'object' || parsed === null) return 'broken';
    if (!parsed.provider || !parsed.baseUrl || !parsed.apiKey) return 'warning';
    return 'healthy';
  } catch {
    return 'broken';
  }
}

export async function readDefaultModel(targetType: TargetType): Promise<string | null> {
  const content = await readRawConfig(targetType);
  if (!content) return null;

  if (targetType === 'hermes') {
    const parsed = parseHermesYaml(content);
    const model = parsed.model as Record<string, unknown> | undefined;
    return (model?.default as string) ?? null;
  }

  if (targetType === 'openclaw') {
    try {
      const parsed = JSON.parse(content);
      return parsed.model ?? null;
    } catch {
      return null;
    }
  }

  if (targetType === 'codex') {
    return parseCodexConfigModel(content);
  }

  return null;
}

export async function writeDefaultModel(targetType: TargetType, model: string): Promise<void> {
  const currentContent = await readRawConfig(targetType);
  let content: string;

  if (targetType === 'hermes') {
    let existing: Record<string, unknown> = {};
    if (currentContent?.trim()) {
      existing = parseHermesYaml(currentContent);
    }
    const m = (existing.model as Record<string, unknown>) || {};
    m.default = model;
    existing.model = m;
    content = mergeHermesYaml(existing, {
      providerType: (m.provider as string) || 'openai-compatible',
      baseUrl: (m.base_url as string) || '',
      defaultModel: model,
      fastModel: (m.default as string) || model,
      reasoningModel: (m.default as string) || model,
      apiKey: '',
    } as Profile | TargetProfile);
  } else if (targetType === 'openclaw') {
    let existing: Record<string, unknown> = {};
    if (currentContent?.trim()) {
      try { existing = JSON.parse(currentContent); } catch { existing = {}; }
    }
    existing.model = model;
    content = JSON.stringify(existing, null, 2);
  } else if (targetType === 'codex') {
    if (currentContent?.trim()) {
      content = updateCodexConfigModel(currentContent, model);
    } else {
      content = generateCodexConfig(model);
    }
  } else {
    throw new Error(`Default model not supported for target: ${targetType}`);
  }

  await writeRawConfig(targetType, content);
}

export async function checkProfileHealth(profile: Profile): Promise<HealthStatus> {
  const targetHealths: HealthStatus[] = [];
  for (const targetType of profile.enabledTargets) {
    const health = await checkTargetHealth(targetType);
    targetHealths.push(health);
  }
  if (targetHealths.every((h) => h === 'healthy')) return 'healthy';
  if (targetHealths.some((h) => h === 'broken')) return 'broken';
  if (targetHealths.some((h) => h === 'warning')) return 'warning';
  return 'unknown';
}

export async function testCodexConnection(
  apiKey: string,
  baseUrl = 'https://api.openai.com/v1'
): Promise<{ ok: boolean; error?: string; models?: string[] }> {
  try {
    const response = await fetch(`${baseUrl}/models`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      signal: AbortSignal.timeout(10000),
    });
    if (!response.ok) {
      const text = await response.text().catch(() => '');
      return { ok: false, error: `HTTP ${response.status}: ${text.slice(0, 200)}` };
    }
    const data = (await response.json()) as { data?: { id: string }[] };
    const models = (data.data || []).map((m) => m.id).sort();
    return { ok: true, models };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

export { readCodexAuth };
